:toc:
= Typical structure of a project


== directory structure

----
dev/
   dev.clj
media/
resources/
   public/
src/
   <project_name>/
      core.clj
      init.clj
      apps/
      endpoints/
      objects/
      modules/
      templates/
project.clj
settings.edn
----

== dev/

Under the dev directory all dev related things should be gathered. This is where you typically put files meant for REPL interaction.

=== dev/dev.clj

Generated by `lein new reverie <project-name>` dev.clj holds interactions for starting the server through the REPL, adding new objects, apps, raw pages, and modules.

== media/

Directory to hold all media files. This runs on the local filesystem.

== resources/

Directory to hold resources to be packaged into the JAR file for production. Queries, publically accessable resources, etc can go under here.

=== resources/public/

Directory to hold publically acessable resources available over HTTP GET. Typically a `resources/public/static/` directory is generated by `lein new reverie <project-name>` and is access as `/static/<URI>`

== src/<project-name>/

Directory that hold all source code meant for production.

=== src/<project-name>/core.clj

Main entry point for the program.

=== src/<project-name>/init.clj

Main configuration/initilization of the project.

=== src/<project-name>/apps

Directory to hold all apps.

=== src/<project-name>/endpoints

Directory to hold all endpoints.

=== src/<project-name>/objects

Directory to hold all objects.

=== src/<project-name>/modules

Directory to hold all modules.

=== src/<project-name>/templates

Directory to hold all templates.

== project.clj

Generated project.clj for leiningen.

== settings.edn

Settings file for reverie that holds all the configuration paramaters.
