= reverie.dev.module

Helper namespace for dealing with modules during development.

== create

Create a new module.

.reverie.dev.module/create
[source,clojure]
----
(create 'mymodule)
(create {:root "project-name.my-dest-for-modules"
         :root-path "project-name/my-dest-for-modules"
         :override? true}
        'mymodule)
----

If the module exists an exception is thrown. Use `:override? true` in `opts` to recreate the module.

NOTE: By default the module will use the project name + modules as the path for the module. Typically it will show up under `project-name/modules/mymodule.clj` with migrations showing up under `project-name/modules/migrations/mymodule`.


== add-migration

Create a new migration for the module.

.reverie.dev.module/add-migration
[source,clojure]
----
(add-migration 'mymodule "foobar")
(add-migration {:root "project-name.my-dest-for-modules"
                :root-path "project-name/my-dest-for-modules"}
        'mymodule "foobar" :entity-name)
(add-migration {:root "project-name.my-dest-for-modules"
                :root-path "project-name/my-dest-for-modules"}
        'mymodule "foobar" "my_table_name")        
----

If the migration exists an exception is thrown. You will need to use `remove-migration` before you can add the same migration again.

TIP: By default the migration will show up under `project-name/modules/migrations/mymodule`.


== remove-migration

Remove an existing migration for the module.

.reverie.dev.module/remove-migration
[source,clojure]
----
(remove-migration 'mymodule "foobar")
(remove-migration {:root "project-name.my-dest-for-modules"
                   :root-path "project-name/my-dest-for-modules"}
        'mymodule "foobar")
----

WARNING: This is a destructive command that will delete files from your hard drive. Use with caution.
